### ISSUE TITLE
Main Game Scene

### ISSUE THREAD

**Issue by isaacsaw25** [isaacsaw25/ZamanPerang#3]
- [x]  Create a clear and intuitive UI layout
- [x]  Base health and health bar mechanics
- [x]  UI: Deploy units.
- [x]  Deploy units: Icon thumbnails to preview characters

**Comment by IvanSawSQ** [comment]
Bugs to be fixed:
Movement of friendly characters (transition from walking to shooting)
Improved shooting and movement animations'
Projectile collision and stacking

Additional features to prioritise:
